### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by nels-o** [danielgwj/capstone12#3]
I strongly encourage you to use `bibtex` instead of [abusing `\footnote`](https://github.com/danielgwj/capstone12/blob/master/RequirementsDoc/reqdoc.tex#L112)

See the [wikibook entry](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management) on the subject for details.

**Comment by danielgwj** [comment]
Replaced all \footnote occurences with \footfullcite with the use of biblertex
